"""Type stubs for the native cndetector._cndetector extension module."""

from __future__ import annotations

class ProblemData:
    def __init__(self, num_nodes: int) -> None: ...
    @staticmethod
    def read_from_adjacency_list_file(filename: str) -> ProblemData: ...
    @staticmethod
    def read_from_dimacs_edge_file(filename: str) -> ProblemData: ...
    def create_original_graph(
        self, budget: int, seed: int
    ) -> CNP_Graph: ...
    def create_original_dcnp_graph(
        self, budget: int, distance: int, seed: int
    ) -> DCNP_Graph: ...
    def add_node(self, node_id: int) -> None: ...
    def add_edge(self, u: int, v: int) -> None: ...
    def get_nodes_set(self) -> set[int]: ...
    def get_adj_list(self) -> list[set[int]]: ...
    def num_nodes(self) -> int: ...

class CNP_Graph:
    def __init__(self) -> None: ...
    def clone(self) -> CNP_Graph: ...
    def update_graph_by_removed_nodes(self, removed_nodes: set[int]) -> None: ...
    def get_reduced_graph_by_removed_nodes(
        self, remove_set: set[int]
    ) -> None: ...
    def add_node(self, node: int) -> None: ...
    def remove_node(self, node: int) -> None: ...
    def remove_best_nodes_from_set(self, candidate_nodes: set[int]) -> None: ...
    def is_node_removed(self, node: int) -> bool: ...
    def get_num_nodes(self) -> int: ...
    def get_removed_nodes(self) -> set[int]: ...
    def set_node_age(self, node: int, age: int) -> None: ...
    def get_objective_value(self) -> int: ...
    def get_random_full_budget_graph(self, seed: int) -> CNP_Graph: ...
    def get_random_partial_graph(
        self, partial_budget: int, seed: int
    ) -> CNP_Graph: ...
    def initialize_components_and_mapping(self) -> None: ...

class DCNP_Graph:
    def __init__(self) -> None: ...
    def clone(self) -> DCNP_Graph: ...
    def update_graph_by_removed_nodes(self, removed_nodes: set[int]) -> None: ...
    def get_reduced_graph_by_removed_nodes(
        self, remove_set: set[int]
    ) -> None: ...
    def add_node(self, node: int) -> None: ...
    def remove_node(self, node: int) -> None: ...
    def is_node_removed(self, node: int) -> bool: ...
    def get_num_nodes(self) -> int: ...
    def get_removed_nodes(self) -> set[int]: ...
    def set_node_age(self, node: int, age: int) -> None: ...
    def get_objective_value(self) -> int: ...
    def get_random_full_budget_graph(self, seed: int) -> DCNP_Graph: ...
    def get_random_partial_graph(
        self, partial_budget: int, seed: int
    ) -> DCNP_Graph: ...
    def build_tree(self) -> None: ...
    def calculate_khop_tree_size(self) -> int: ...
    def find_best_node_to_remove(self) -> int: ...
    def find_best_node_to_add(self) -> int: ...
    def random_select_node_to_remove(self) -> int: ...

class SolverConfig:
    population_size: int
    thread_count: int
    stagnation_threshold: int
    interaction_period: int
    seed: int
    relaxation_coefficient: float
    backbone_rate: float
    display_interval: float
    max_runtime: float
    search: str
    l2ns: L2NSConfig
    def __init__(self) -> None: ...

class L2NSConfig:
    allowable_idle_iterations: int
    min_destroy_size: int
    max_destroy_size: int
    idle_iteration_cap: int
    idle_iteration_floor: int
    impact_selection_rate: float
    randomize_destroy_size: bool
    adaptive_max_idle_iterations: int
    adaptive_min_destroy_size: int
    adaptive_max_destroy_size: int
    adaptive_growth_interval: int
    def __init__(self) -> None: ...

class IterationEvent:
    iteration: int
    elapsed: float
    best_objective: int
    population_size: int

class HPCReport:
    hpc_triggered: bool
    candidate_obj_value: int
    improved_main_best: bool

class HPCEvent:
    iteration: int
    report: HPCReport

class LocalSearchResult:
    solution: set[int]
    obj_value: int

class DualPopulation:
    def __init__(
        self,
        original_graph: CNP_Graph,
        main_budget: int,
        auxiliary_budget: int,
        config: SolverConfig,
    ) -> None: ...
    def initialize(self) -> tuple[set[int], int]: ...
    def advance_one_generation(self) -> None: ...
    def drain_iteration_events(self) -> list[IterationEvent]: ...
    def drain_hpc_events(self) -> list[HPCEvent]: ...
    def get_best_solution(self) -> tuple[set[int], int]: ...
    def get_main_population(self) -> list[tuple[set[int], int]]: ...
    def get_main_population_size(self) -> int: ...
    def get_main_generation_count(self) -> int: ...

class DCNPDualPopulation:
    def __init__(
        self,
        original_graph: DCNP_Graph,
        main_budget: int,
        auxiliary_budget: int,
        config: SolverConfig,
    ) -> None: ...
    def initialize(self) -> tuple[set[int], int]: ...
    def advance_one_generation(self) -> None: ...
    def drain_iteration_events(self) -> list[IterationEvent]: ...
    def drain_hpc_events(self) -> list[HPCEvent]: ...
    def get_best_solution(self) -> tuple[set[int], int]: ...
    def get_main_population(self) -> list[tuple[set[int], int]]: ...
    def get_main_population_size(self) -> int: ...
    def get_main_generation_count(self) -> int: ...

def run_l2ns(
    graph: CNP_Graph, seed: int, config: L2NSConfig
) -> LocalSearchResult: ...
def run_dcnp_l2ns(
    graph: DCNP_Graph, seed: int, config: L2NSConfig
) -> LocalSearchResult: ...
def resolve_l2ns_config(config: SolverConfig) -> L2NSConfig: ...
def set_max_threads(count: int) -> None: ...
def get_max_threads() -> int: ...
def deterministic_seed(
    base_seed: int, stream_id: int, iteration: int = 0, slot: int = 0
) -> int: ...
