"""Type stubs for the native pypdms._pypdms extension module."""

from __future__ import annotations

class ProblemData:
    def __init__(self, num_nodes: int) -> None: ...
    @staticmethod
    def read_from_adjacency_list_file(filename: str) -> ProblemData: ...
    @staticmethod
    def read_from_dimacs_edge_file(filename: str) -> ProblemData: ...
    def create_original_graph(
        self, budget: int, seed: int
    ) -> CNP_Graph: ...
    def create_original_dcnp_graph(
        self, budget: int, distance: int, seed: int
    ) -> DCNP_Graph: ...
    def add_node(self, node_id: int) -> None: ...
    def add_edge(self, u: int, v: int) -> None: ...
    def get_nodes_set(self) -> set[int]: ...
    def get_adj_list(self) -> list[set[int]]: ...
    def num_nodes(self) -> int: ...

class CNP_Graph:
    def __init__(self) -> None: ...
    def clone(self) -> CNP_Graph: ...
    def update_graph_by_removed_nodes(self, removed_nodes: set[int]) -> None: ...
    def get_reduced_graph_by_removed_nodes(
        self, remove_set: set[int]
    ) -> None: ...
    def add_node(self, node: int) -> None: ...
    def remove_node(self, node: int) -> None: ...
    def remove_best_nodes_from_set(self, candidate_nodes: set[int]) -> None: ...
    def is_node_removed(self, node: int) -> bool: ...
    def get_num_nodes(self) -> int: ...
    def get_removed_nodes(self) -> set[int]: ...
    def set_node_age(self, node: int, age: int) -> None: ...
    def get_objective_value(self) -> int: ...
    def get_random_feasible_graph(self, seed: int) -> CNP_Graph: ...
    def get_random_partial_graph(
        self, partial_budget: int, seed: int
    ) -> CNP_Graph: ...
    def initialize_components_and_mapping(self) -> None: ...

class DCNP_Graph:
    def __init__(self) -> None: ...
    def clone(self) -> DCNP_Graph: ...
    def update_graph_by_removed_nodes(self, removed_nodes: set[int]) -> None: ...
    def get_reduced_graph_by_removed_nodes(
        self, remove_set: set[int]
    ) -> None: ...
    def add_node(self, node: int) -> None: ...
    def remove_node(self, node: int) -> None: ...
    def is_node_removed(self, node: int) -> bool: ...
    def get_num_nodes(self) -> int: ...
    def get_removed_nodes(self) -> set[int]: ...
    def set_node_age(self, node: int, age: int) -> None: ...
    def get_objective_value(self) -> int: ...
    def get_random_feasible_graph(self, seed: int) -> DCNP_Graph: ...
    def get_random_partial_graph(
        self, partial_budget: int, seed: int
    ) -> DCNP_Graph: ...
    def build_tree(self) -> None: ...
    def calculate_khop_tree_size(self) -> int: ...
    def find_best_node_to_remove(self) -> int: ...
    def find_best_node_to_add(self) -> int: ...
    def random_select_node_to_remove(self) -> int: ...

class SolverConfig:
    population_size: int
    offspring_count: int
    transfer_interval: int
    seed: int
    partial_ratio: float
    beta: float
    display_interval: float
    max_runtime: float
    search: str
    def __init__(self) -> None: ...

class CHNSConfig:
    max_idle_steps: int
    theta: float
    min_batch_size: int
    max_batch_size: int
    batch_idle_threshold: int
    randomize_batch_and_idle: bool
    random_batch_min: int
    random_batch_max: int
    random_idle_product: int
    random_min_idle_steps: int
    random_max_idle_steps: int
    def __init__(self) -> None: ...

class IterationEvent:
    iteration: int
    elapsed: float
    best_objective: int
    population_size: int

class ExchangeReport:
    exchange_triggered: bool
    first_population_candidate_obj: int
    first_population_improved_best: bool

class ExchangeEvent:
    iteration: int
    report: ExchangeReport

class LocalSearchResult:
    solution: set[int]
    obj_value: int

class DualPopulation:
    def __init__(
        self,
        original_graph: CNP_Graph,
        feasible_budget: int,
        infeasible_budget: int,
        config: SolverConfig,
    ) -> None: ...
    def initialize(self) -> tuple[set[int], int]: ...
    def advance_one_generation(self) -> None: ...
    def drain_iteration_events(self) -> list[IterationEvent]: ...
    def drain_exchange_events(self) -> list[ExchangeEvent]: ...
    def get_best_feasible_solution(self) -> tuple[set[int], int]: ...
    def get_feasible_population(self) -> list[tuple[set[int], int]]: ...
    def get_feasible_population_size(self) -> int: ...
    def get_feasible_iteration_count(self) -> int: ...

def run_chns(
    graph: CNP_Graph, seed: int, config: CHNSConfig
) -> LocalSearchResult: ...
def run_dcnp_chns(
    graph: DCNP_Graph, seed: int, config: CHNSConfig
) -> LocalSearchResult: ...
def resolve_chns_config(config: SolverConfig) -> CHNSConfig: ...
def deterministic_seed(
    base_seed: int, stream_id: int, iteration: int = 0, slot: int = 0
) -> int: ...
