from __future__ import annotations

DEFAULT_POPULATION_SIZE = 6
DEFAULT_OFFSPRING_COUNT = 1
DEFAULT_TRANSFER_INTERVAL = 50
DEFAULT_PARTIAL_RATIO = 0.95
DEFAULT_BETA = 0.9
DEFAULT_DISPLAY_INTERVAL = 1.0

PACKAGE_LOGGER_NAME = "pypdms"

CNP = "CNP"
DCNP = "DCNP"
CHNS = "CHNS"
